### ISSUE TITLE
API_URI not setting

### ISSUE THREAD

**Issue by riipeckx** [mirumee/saleor-storefront#942]
### What I'm trying to achieve
Set the API_URI env in Docker Swarm by setting it in my docker-compose.yml
### Steps to reproduce the problem
1. Add this code to docker-compose.yml
```yml
store:
    image: zeroexistence/saleor-storefront:2.11
    environment:
      - API_URI=http://core:8000/graphql/
    networks:
      - backend
```

2. execute `docker stack deploy -c docker-compose.yml <stackName>`

3. Head to the website

### What I expected to happen
The container connects to the core one through the `API_URI` address contained in the docker-compose.yml

### Screenshots
![image](https://user-images.githubusercontent.com/18305797/98676340-c4761080-235b-11eb-8c9a-344528f7e6d5.png)
The container connects through the default url, not the `API_URI` address contained in the docker-compose.yml

**System information**
Operating system: Linux Debian 10 - Docker 19.03.13
Browser: Chrome Version 86.0.4240.183 (Official Build) (64-bit)
